// examples/jacare-island-vue/src/JacareTip.vue
<script setup>
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { mountIsland } from '@jacare/core/island'
import TipIsland from './islands/TipIsland.jcr'

const props = defineProps({
  topic: { type: String, default: 'islands' },
})

const host = ref(null)
let island

onMounted(() => {
  if (!host.value) return
  island = mountIsland(host.value, TipIsland, {
    props: { topic: props.topic },
    shadow: true,
  })
})

watch(
  () => props.topic,
  (topic) => {
    island?.update({ topic })
  },
)

onBeforeUnmount(() => {
  island?.()
  island = undefined
})
</script>

<template>
  <div ref="host" class="island-host" />
</template>

// examples/jacare-island-react/src/JacareTip.jsx
import { useEffect, useRef } from 'react'
import { mountIsland } from '@jacare/core/island'
import TipIsland from './islands/TipIsland.jcr'

export function JacareTip({ topic = 'islands' }) {
  const hostRef = useRef(null)
  const islandRef = useRef(null)

  useEffect(() => {
    const el = hostRef.current
    if (!el) return undefined
    const island = mountIsland(el, TipIsland, {
      props: { topic },
      shadow: true,
    })
    islandRef.current = island
    return () => {
      island()
      islandRef.current = null
    }
  }, [])

  useEffect(() => {
    islandRef.current?.update({ topic })
  }, [topic])

  return <div ref={hostRef} className="island-host" />
}
