// examples/jacare-island-vue/src/JacareCounter.vue
<script setup>
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { mountIsland } from '@jacare/core/island'
import CounterIsland from './islands/CounterIsland.jcr'

const props = defineProps({
  start: { type: Number, default: 0 },
  label: { type: String, default: 'Clicks' },
})

const host = ref(null)
let island

onMounted(() => {
  if (!host.value) return
  island = mountIsland(host.value, CounterIsland, {
    props: { start: props.start, label: props.label },
  })
})

watch(
  () => [props.start, props.label],
  ([start, label]) => {
    island?.update({ start, label })
  },
)

onBeforeUnmount(() => {
  island?.()
  island = undefined
})
</script>

<template>
  <div ref="host" class="island-host" />
</template>

// examples/jacare-island-react/src/JacareCounter.jsx
import { useEffect, useRef } from 'react'
import { mountIsland } from '@jacare/core/island'
import CounterIsland from './islands/CounterIsland.jcr'

export function JacareCounter({ start = 0, label = 'Clicks' }) {
  const hostRef = useRef(null)
  const islandRef = useRef(null)

  useEffect(() => {
    const el = hostRef.current
    if (!el) return undefined
    const island = mountIsland(el, CounterIsland, {
      props: { start, label },
    })
    islandRef.current = island
    return () => {
      island()
      islandRef.current = null
    }
  }, [])

  useEffect(() => {
    islandRef.current?.update({ start, label })
  }, [start, label])

  return <div ref={hostRef} className="island-host" />
}
