// examples/jacare-island-angular/src/jacare-counter.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  ViewChild,
} from '@angular/core'
import { mountIsland } from '@jacare/core/island'
import CounterIsland from './islands/CounterIsland.jcr'

@Component({
  selector: 'app-jacare-counter',
  standalone: true,
  template: `<div #host class="island-host"></div>`,
})
export class JacareCounterComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input() start = 0
  @Input() label = 'Clicks'

  @ViewChild('host', { static: true })
  host!: ElementRef<HTMLDivElement>

  private dispose?: () => void
  private ready = false

  ngAfterViewInit(): void {
    this.ready = true
    this.remount()
  }

  ngOnChanges(): void {
    if (this.ready) this.remount()
  }

  ngOnDestroy(): void {
    this.dispose?.()
    this.dispose = undefined
  }

  private remount(): void {
    this.dispose?.()
    this.dispose = mountIsland(this.host.nativeElement, CounterIsland, {
      props: { start: this.start, label: this.label },
    })
  }
}

// examples/jacare-island-vue/src/JacareCounter.vue
<script setup>
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { mountIsland } from '@jacare/core/island'
import CounterIsland from './islands/CounterIsland.jcr'

const props = defineProps({
  start: { type: Number, default: 0 },
  label: { type: String, default: 'Clicks' },
})

const host = ref(null)
let dispose

function remount() {
  dispose?.()
  dispose = undefined
  if (!host.value) return
  dispose = mountIsland(host.value, CounterIsland, {
    props: { start: props.start, label: props.label },
  })
}

onMounted(remount)
watch(() => [props.start, props.label], remount)
onBeforeUnmount(() => {
  dispose?.()
  dispose = undefined
})
</script>

<template>
  <div ref="host" class="island-host" />
</template>
